### ISSUE TITLE
Requirements update

### ISSUE THREAD

**Issue by ghost** [lekoala/silverstripe-pure-modal#11]
Would it be possible to do a new release with requirements updated for SS5? I've tested this locally with the below on an SS5 installation and I had no issues.

```
"require": {
    "php": "^8.1",
    "silverstripe/recipe-plugin": "^2",
    "silverstripe/admin": "^2",
    "silverstripe/framework": "^5"
}
```

**Comment by lekoala** [comment]
yes i'm currently working on it it should be there soon. if not today next week

**Comment by ghost** [comment]
Awesome, thank you very much!!

**Comment by lekoala** [comment]
added in master https://github.com/lekoala/silverstripe-pure-modal/commit/170bfc9e87ab681c5d12de973cca2b78acfc3949

**Comment by ghost** [comment]
That's all working fine for me. Thanks for sorting that 👍.
