### ISSUE TITLE
PureModal: css classes are hardcoded

### ISSUE THREAD

**Issue by wernerkrauss** [lekoala/silverstripe-pure-modal#12]
adding `->addExtraClass('font-icon font-icon-install');` on a PureModal has no effect, cause css classes are hardcoded in PureModal.ss

It's be great if I could also add icons to a modal button.

**Comment by lekoala** [comment]
true, never had to change it in my project :-)

here you go
https://github.com/lekoala/silverstripe-pure-modal/releases/tag/1.2.1

**Comment by wernerkrauss** [comment]
Thanks! Works now.
