### ISSUE TITLE
Unable to adjust button type/icon

### ISSUE THREAD

**Issue by lozcalver** [lekoala/silverstripe-pure-modal#5]
Thanks for creating this module! A couple of minor issues:

Using `setButtonIcon('cancel-circled')` results in HTML being rendered as it’s automatically escaped:

<img width="479" alt="Screenshot 2022-02-17 at 17 03 26" src="https://user-images.githubusercontent.com/1655548/154532823-c076b328-4f83-4398-b223-509eea3e4630.png">

There’s also no `setButtonType()` method like the cms-actions module, so I tried working around both issues by using: `addExtraClass('btn-danger font-icon-cancel-circled')` but that gets overwritten by hardcoded classes in the template.

**Comment by lekoala** [comment]
@kinglozzer good catch !
fixed in https://github.com/lekoala/silverstripe-pure-modal/releases/tag/1.1.2

**Comment by lozcalver** [comment]
Thanks! ❤️
