### ISSUE TITLE
Checkbox fields are always hidden

### ISSUE THREAD

**Issue by lozcalver** [lekoala/silverstripe-pure-modal#7]
Checkbox fields in the modal window are always hidden by this CSS rule:

https://github.com/lekoala/silverstripe-pure-modal/blob/7a75f02bf8338e15c36d87ef104423649bac122e/client/pure-modal.css#L1-L3

Removing this causes a checkbox to show up next to the button to open the modal, I’m not sure what those checkboxes are used for

**Comment by lekoala** [comment]
ah yes, it's used to make the css only modal.
https://github.com/lekoala/silverstripe-pure-modal/blob/7a75f02bf8338e15c36d87ef104423649bac122e/templates/LeKoala/PureModal/PureModal.ss#L7
https://github.com/lekoala/silverstripe-pure-modal/blob/7a75f02bf8338e15c36d87ef104423649bac122e/client/pure-modal.css#L97
but the css rule could be more specific to only target that specific checkbox

**Comment by lekoala** [comment]
@kinglozzer fixed
https://github.com/lekoala/silverstripe-pure-modal/releases/tag/1.1.4
