### ISSUE TITLE
Cannot use UploadField

### ISSUE THREAD

**Issue by gurucomkz** [lekoala/silverstripe-pure-modal#8]
Trying to add `UploadField` in CMS results in 
```
[Emergency] Uncaught LogicException: Field must be associated with a form to call Link(). Please use $field->setForm($form);
```

Do you have any idea how to make this work?

**Comment by lekoala** [comment]
@gurucomkz and what if you call setForm on your upload field ? or on the FieldList ? does it change anything ?
the uploadfield is probably not going to work as expected anyway but that's where i would start

**Comment by lekoala** [comment]
@gurucomkz is https://github.com/lekoala/silverstripe-pure-modal/releases/tag/1.1.9 fixing the issue ?

**Comment by lekoala** [comment]
closing this, feel free to reopen if needed

**Comment by wernerkrauss** [comment]
Hi, I tried an UploadField in a Modal and I get: 

> I can't handle sub-URLs on class SilverStripe\Forms\FormRequestHandler. 

With good ol' FileField I don't see the uploaded file in any POST data.

Do you know a way to upload a file to an action/modal? I'd like to process this file without saving it to assets.

**Comment by lekoala** [comment]
hi @wernerkrauss the filefield should work fine, because that's how i'm using it in a project of mine to display a modal where the user can upload a file

should be something like this

in your getCMSFields

   $upload_stuff= new PureModal('upload_stuff', 'Upload', 'Upload some stuff');
            $fields->addFieldToTab('Root.Upload', $upload_stuff);
            $upload_stuff->setIframeAction('upload_stuff_form');
            $upload_stuff->setIframeTop(true);

in your modeladmin

    /**
     * @param HTTPRequest $req
     * @return string
     * @throws ValidationException
     */
    public function upload_stuff_form(HTTPRequest $req)
    {
        $rec= $this->getRequestedRecord();
        $fields = new FieldList([
            new FileField('File'),
            new HiddenField('RecID', null, $Rec->ID),
        ]);
        $actions = new FieldList([
            new FormAction('doUpload', 'Upload')
        ]);
        $form = new Form(Controller::curr(), 'UploadMyStuff', $fields, $actions);
        return $this->renderDialog(['Form' => $form]);
    }

    /**
     * Render a dialog
     *
     * @param array $customFields
     * @return string
     */
    protected function renderDialog($customFields = null)
    {
        // Set empty content by default otherwise it will render the full page
        if (empty($customFields['Content'])) {
            $customFields['Content'] = '';
        }
        return $this->renderWith('SilverStripe\\Admin\\CMSDialog', $customFields);
    }


    /**
     * @param HTTPRequest $req
     * @return DBHTMLText
     * @throws ValidationException
     */
    public function UploadMyStuff(HTTPRequest $req)
    {
        $file = $req->postVar('File');
        if (!$file) {
            return $this->dialogMessage('No file!', "error");
        }
        if ($file['error']) {
            return $this->dialogMessage('There was an error while uploading the file', 'error');
        }

       var_dump($file); // Do something with file

**Comment by wernerkrauss** [comment]
I used PureModalAction in an Extension's `updateCMSActions` method:

```
            $importAction = PureModalAction::create('doImport', _t(self::class . '.DOIMPORT', 'Import Translations'));
            $importAction->setDialogButtonTitle(_t(self::class . '.IMPORTHEADER', 'Import Translations to {locale}',
                ['locale' => $this->getOwner()->Locale]));
            $importAction->setFieldList($this->getImportFields());
            $importAction->setButtonIcon(SilverStripeIcons::ICON_PRINT);
            $importAction->setShouldRefresh(true);
            $actions->push($importAction);
```
and 
```
    public function getImportFields(): FieldList
    {
        $info = HeaderField::create('ImportInfo', _t(self::class . '.IMPORTINFO',
            'some info text.'));

        $upload = FileField::create('ImportUpload', _t(self::class . '.IMPORTUPLOAD', 'Upload stuff'));
        $upload->setAllowedExtensions(['yml']);

        return FieldList::create([
            $info,
            $upload
        ]);
    }
```
Text field data was submitted, but I didn't find a PostVar for ImportUpload in xdebug.

I'll try your solution now, it'd be nice if I could have this in the actions below...

**Comment by lekoala** [comment]
yes, the pure modal action doesn't submit files, that is a known limitation unfortunately

i believe it's due to how the form is submitted by LeftAndMain see here

https://github.com/silverstripe/silverstripe-admin/blob/0517656dbb9c6ba38522a11c379a64c11f640162/client/src/legacy/LeftAndMain.js#L539-L546

it should really be replaced by a simple FormData that should work fine instead

https://stackoverflow.com/questions/41684385/how-to-add-file-value-with-jquery-serialize

**Comment by wernerkrauss** [comment]
Just trying your code, but I don't see where `$this->getRequestedRecord()`comes from. A google search only shows this module's README ...

**Comment by lekoala** [comment]
oops sorry yes that is a helper method from my own module

https://github.com/lekoala/silverstripe-base/blob/6d50c23986bb273639907cc2518275ba74a87b36/src/Admin/BaseModelAdmin.php#L179

you should be able to replace it with a simpler approach i don't remember exactly what is passed to the method itself
