### ISSUE TITLE
Modal form doesn't submit

### ISSUE THREAD

**Issue by lozcalver** [lekoala/silverstripe-pure-modal#9]
I think [this commit](https://github.com/lekoala/silverstripe-pure-modal/commit/6f97b90440e8ed4c2c8bb0c6011bd4cea89f0437) might be missing some code - I can’t seem to find any reference to `$SubmitOnClickScript` outside of the template, and when I click the submit button nothing happens 😞 

Edit: just been testing different versions, 1.1.4 works as expected but from 1.1.5 the form doesn’t submit for me when clicking the submit button

If it helps, my actions are set up with:

```php
public function getCMSActions(): FieldList
{
    $this->beforeExtending('updateCMSActions', function (FieldList $actions) {
        if ($this->Status !== 'Pending') {
            return;
        }

        $doApprove = PureModalAction::create('doApprove', 'Approve');
        $doApprove->setButtonType('primary');
        $doApprove->setButtonIcon('check-mark-circle');
        $doApprove->setFieldList(FieldList::create(
            TextareaField::create('StatusDetail', 'Message')
                ->setDescription('Optional, shown to the member as extra information for approval decision')
        ));
        $doApprove->setShouldRefresh(true);
        $doApprove->setDialogButtonTitle('Approve request');
        $actions->push($doApprove);

        $doReject = PureModalAction::create('doReject', 'Reject');
        $doReject->setButtonType('danger');
        $doReject->setButtonIcon('cancel-circled');
        $doReject->setFieldList(FieldList::create(
            TextareaField::create('StatusDetail', 'Message')
                ->setDescription('Optional, shown to the member as extra information for rejection decision')
        ));
        $doReject->setShouldRefresh(true);
        $doReject->setDialogButtonTitle('Reject request');
        $actions->push($doReject);
    });

    return parent::getCMSActions();
}
```

**Comment by lekoala** [comment]
@kinglozzer yes you are right, i don't know how i missed that bit. actually, it's due to the "move_modal_to_body" option (which was set to true by default, but i set it back to false) and a missing script. It should be all good now.

https://github.com/lekoala/silverstripe-pure-modal/releases/tag/1.1.8

**Comment by lozcalver** [comment]
Thanks, that fixes it ❤️ 

I did quickly test `move_modal_to_body` but it doesn’t seem to work - I’ll leave that feature disabled for now 😄
